services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: ["bun", "run", "dev"]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://lebot:lebot@postgres:5432/lebot
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: lebot
      POSTGRES_PASSWORD: lebot
      POSTGRES_DB: lebot
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
